import { PopupDirection } from "./FieldTypes";
import { GComponent } from "./GComponent";
import { GObject } from "./GObject";
import { Window } from "./Window";
export declare class GRoot extends GComponent {
    private _modalLayer;
    private _popupStack;
    private _justClosedPopups;
    private _modalWaitPane;
    private _tooltipWin;
    private _defaultTooltipWin;
    static get inst(): GRoot;
    static findFor(obj: GObject): GRoot;
    constructor();
    private applyScaleFactor;
    showWindow(win: Window): void;
    hideWindow(win: Window): void;
    hideWindowImmediately(win: Window): void;
    bringToFront(win: Window): void;
    showModalWait(msg?: string): void;
    closeModalWait(): void;
    closeAllExceptModals(): void;
    closeAllWindows(): void;
    getTopWindow(): Window;
    get modalLayer(): GObject;
    get hasModalWindow(): boolean;
    get modalWaiting(): boolean;
    showPopup(popup: GObject, target?: GObject, dir?: PopupDirection): void;
    togglePopup(popup: GObject, target?: GObject, dir?: PopupDirection): void;
    hidePopup(popup?: GObject): void;
    get hasAnyPopup(): boolean;
    private closePopup;
    showTooltips(msg: string): void;
    showTooltipsWin(tooltipWin: GObject, xx?: number, yy?: number): void;
    hideTooltips(): void;
    playOneShotSound(url: string, volumeScale?: number): void;
    private adjustModalLayer;
    checkPopups(): void;
    private __stageTouchBegin;
}
