import { Audio } from 'three';
import { PixelHitTestData } from "../core/hittest/PixelHitTest";
import { Frame } from "../core/MovieClip";
import { NTexture } from "../core/NTexture";
import { BitmapFont } from "../core/text/BitmapFont";
import { ByteBuffer } from "../utils/ByteBuffer";
import { Rect } from "../utils/Rect";
import { UIPackage } from "./UIPackage";
export declare class PackageItem {
    owner: UIPackage;
    type: number;
    objectType: number;
    id: string;
    name: string;
    width: number;
    height: number;
    file: string;
    decoded?: boolean;
    rawData?: ByteBuffer;
    highResolution?: Array<string>;
    branches?: Array<string>;
    scale9Grid?: Rect;
    scaleByTile?: boolean;
    tileGridIndice?: number;
    smoothing?: boolean;
    texture?: NTexture;
    pixelHitTestData?: PixelHitTestData;
    interval?: number;
    repeatDelay?: number;
    swing?: boolean;
    frames?: Frame[];
    extensionType?: any;
    bitmapFont?: BitmapFont;
    audioBuffer?: AudioBuffer;
    sound?: Audio;
    constructor();
    load(): Object;
    getBranch(): PackageItem;
    getHighResolution(): PackageItem;
    toString(): string;
}
